In [1]:
import torch
from torch import nn
import torchvision
from torchvision import datasets
from torchvision import transforms
from torchvision.transforms import ToTensor
import numpy as np
import matplotlib.pyplot as plt
import pandas

print(torch.__version__)
print(torchvision.__version__)

2.1.0+cu118
0.16.0+cu118


In [2]:
training_dataset = datasets.FashionMNIST(root = "data",
                                         train = True,
                                         transform = ToTensor(),
                                         target_transform = None,
                                         download = True)

test_dataset = datasets.FashionMNIST(root = "data",
                                     train = False,
                                     transform = ToTensor(),
                                     target_transform = None,
                                     download = True)

100%|██████████| 26421880/26421880 [00:00<00:00, 106310942.61it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 96941959.72it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw




100%|██████████| 4422102/4422102 [00:00<00:00, 65057753.05it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 21613890.88it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [ ]:
image , label = training_dataset[0]
image.shape , label

(torch.Size([1, 28, 28]), 9)

## As we can see the train data have 60,000 images so we need to make mini-batches
## But first we have to convert our pytorch dataset into a python iterable

In [3]:
from torch.utils.data import DataLoader

Batch_Size = 32

train_dataloader = DataLoader(dataset = training_dataset , batch_size= Batch_Size , shuffle=True)

test_dataloader = DataLoader(dataset = test_dataset , batch_size= Batch_Size , shuffle=False)

In [13]:
test_dataloader

In [8]:
train_features_batch , train_labels_batch = next(iter(train_dataloader))

train_features_batch.shape

torch.Size([32])
torch.Size([32, 1, 28, 28])


In [7]:
class_names = training_dataset.classes
flatten_model = nn.Flatten()

x = train_features_batch[0]

output = flatten_model(x)
output

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

## NN Model

In [ ]:
class FashionMNISTModel_0(nn.Module):
  def __init__(self,
               input_features: int,
               hidden_units: int,
               output_features: int):
    super().__init__()

    self.layer_stack = nn.Sequential(
        nn.Flatten(),
        nn.Linear(in_features = input_features,
                  out_features = hidden_units),
        nn.Linear(in_features = hidden_units,
                  out_features = hidden_units),
        nn.Linear(in_features = hidden_units,
                  out_features = output_features)
    )

  def forward(self,x):
    return self.layer_stack(x)

In [ ]:
torch.manual_seed(42)

model_0 = FashionMNISTModel_0(input_features = 784,
                            hidden_units = 10,
                            output_features = len(class_names))

model_0

FashionMNISTModel_0(
  (layer_stack): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=784, out_features=10, bias=True)
    (2): Linear(in_features=10, out_features=10, bias=True)
    (3): Linear(in_features=10, out_features=10, bias=True)
  )
)

In [ ]:
list(model_0.parameters())

[Parameter containing:
 tensor([[ 0.0273,  0.0296, -0.0084,  ..., -0.0142,  0.0093,  0.0135],
         [-0.0188, -0.0354,  0.0187,  ..., -0.0106, -0.0001,  0.0115],
         [-0.0008,  0.0017,  0.0045,  ..., -0.0127, -0.0188,  0.0059],
         ...,
         [-0.0116,  0.0273, -0.0344,  ...,  0.0176,  0.0283, -0.0011],
         [-0.0230,  0.0257,  0.0291,  ..., -0.0187, -0.0087,  0.0001],
         [ 0.0176, -0.0147,  0.0053,  ..., -0.0336, -0.0221,  0.0205]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0093,  0.0283, -0.0033,  0.0255,  0.0017,  0.0037, -0.0302, -0.0123,
          0.0018,  0.0163], requires_grad=True),
 Parameter containing:
 tensor([[ 0.0614, -0.0687,  0.0021,  0.2718,  0.2109,  0.1079, -0.2279, -0.1063,
           0.2019,  0.2847],
         [-0.1495,  0.1344, -0.0740,  0.2006, -0.0475, -0.2514, -0.3130, -0.0118,
           0.0932, -0.1864],
         [ 0.2488,  0.1500,  0.1907,  0.1457, -0.3050, -0.0580,  0.1643,  0.1565,
          -0.2877, -0.1792]

## Now Time To setup Loss and Optimizer

In [ ]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(params = model_0.parameters(),
                             lr = 0.1)

def accuracy_fn(y_true, y_pred):
    """Calculates accuracy between truth labels and predictions.

    Args:
        y_true (torch.Tensor): Truth labels for predictions.
        y_pred (torch.Tensor): Predictions to be compared to predictions.

    Returns:
        [torch.float]: Accuracy value between y_true and y_pred, e.g. 78.45
    """
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct / len(y_pred)) * 100
    return acc



In [ ]:
from timeit import default_timer as timer
def print_train_time(start :float,
                     end: float ,
                     device : torch.device=None):
  timee = end - start
  print(f"The time taken is: {timee}")
  return timee

'''
The functionality works like this

start_time = timer()
....some code.....
end_time = timer()
'''

'\nThe functionality works like this \n\nstart_time = timer()\n....some code.....\nend_time = timer()\n'

## Training And testing Loop

* We will lopp through train dataset as well as training and testing batches at the same time

* We can use a library called tqdm which is used to add a progress bar in our programme


>

In [ ]:
from tqdm.auto import tqdm

torch.manual_seed(42)

epochs = 3
train_timer_start = timer()

for epoch in tqdm(range(epochs)):
  print(f"epoch no. {epoch} \n-------- ")

  train_loss , train_acc = 0,0

  for batch , (X,y) in enumerate(train_dataloader):

    model_0.train()

    y_preds = model_0(X)

    loss = loss_fn(y_preds , y)
    train_loss += loss

    #train_acc += accuracy_fn(y , y_preds)


    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if batch%400 ==0 :
      print(f"Looking at {batch * len(X)}/{len(train_dataloader.dataset)}")

  train_loss /= len(train_dataloader)
  #train_acc /= len(train_dataloader)

  test_loss ,test_acc = 0 ,0

  model_0.eval()

  with torch.inference_mode():
    for X_test,y_test in test_dataloader:

      test_pred = model_0(X_test)

      test_loss += loss_fn(test_pred , y_test)
      test_acc += accuracy_fn(y_test , test_pred.argmax(dim=1))

    test_loss /= len(test_dataloader)
    test_acc /= len(test_dataloader)

  print(f"Train loss: {train_loss:.4f} | Test Loss: {test_loss:.4f} | Test Accuracy: {test_acc:.4f}")

train_timer_end = timer()

total_time_taken = print_train_time(train_timer_start,
                                    train_timer_end)




  0%|          | 0/3 [00:00<?, ?it/s]

epoch no. 0 
-------- 
Looking at 0/60000
Looking at 12800/60000
Looking at 25600/60000
Looking at 38400/60000
Looking at 51200/60000
Train loss: 0.6355 | Test Loss: 0.5304 | Test Accuracy: 80.7907
epoch no. 1 
-------- 
Looking at 0/60000
Looking at 12800/60000
Looking at 25600/60000
Looking at 38400/60000
Looking at 51200/60000
Train loss: 0.4999 | Test Loss: 0.4911 | Test Accuracy: 82.6278
epoch no. 2 
-------- 
Looking at 0/60000
Looking at 12800/60000
Looking at 25600/60000
Looking at 38400/60000
Looking at 51200/60000
Train loss: 0.4741 | Test Loss: 0.4989 | Test Accuracy: 82.8574
The time taken is: 29.741005002999998


## Making Predictions To evaluate model 0 performance

In [ ]:
torch.manual_seed(42)

def eval_model(model: torch.nn.Module,
               data_loader: torch.utils.data.DataLoader,
               loss_fn: torch.nn.Module,
               accuracy_fn):
  loss ,acc =0,0

  model.eval()

  with torch.inference_mode():

    for X,y in data_loader:

      y_pred = model(X)

      loss += loss_fn(y_pred , y)
      acc += accuracy_fn(y , y_pred.argmax(dim=1))

    loss /= len(data_loader)
    acc /= len(data_loader)

  return {"model" : model.__class__.__name__,
          "model loss": loss.item(),
          "model accuracy": acc}



In [ ]:
model_0_results = eval_model(model_0 , test_dataloader , nn.CrossEntropyLoss() , accuracy_fn)
model_0_results

{'model': 'FashionMNISTModel_0',
 'model loss': 0.4988920986652374,
 'model accuracy': 82.85742811501598}

## MODEL 2

## Now we will try to make our model with non-linear activation functions to add non-linearity to our model to increase accuracy ofc.
## But we can do a bunch of other stuff to increase accuracy as well.

In [ ]:
class FashionMNISTModel_1(nn.Module):
  def __init__(self,
               input_features: int,
               hidden_units: int,
               output_features: int):
    super().__init__()

    self.layer_stack = nn.Sequential(
        nn.Flatten(),
        nn.Linear(in_features = input_features,
                  out_features = hidden_units),
        nn.ReLU(),
        nn.Linear(in_features = hidden_units,
                  out_features = hidden_units),
        nn.ReLU(),
        nn.Linear(in_features = hidden_units,
                  out_features = output_features)
    )

  def forward(self,x):
    return self.layer_stack(x)

In [ ]:
torch.manual_seed(42)
model_1 = FashionMNISTModel_1(input_features = 784,
                            hidden_units = 10,
                            output_features = len(class_names))

In [ ]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(params = model_1.parameters(),
                             lr = 0.01)

# Now we will functionize our training and testing loop so that we can just pass the parameters in a function which we have already hardcodded

In [ ]:
def training_model(model: torch.nn.Module,
                   dataloader: torch.utils.data.DataLoader,
                   loss_fn: torch.nn.Module,
                   optimizer: torch.optim.Optimizer,
                   accuracy_fn):


  train_loss , train_acc = 0,0

  for batch ,(X,y) in enumerate(dataloader):

    model.train()

    y_preds = model(X)

    loss = loss_fn(y_preds , y)
    train_loss += loss

    train_acc += accuracy_fn(y , y_preds.argmax(dim=1))

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

  train_loss /= len(dataloader)
  train_acc /= len(dataloader)

  print(f"Training Loss: {train_loss:.4f} | Training Accuracy: {train_acc:.4f}")



In [ ]:
def testing_model(model: torch.nn.Module,
                  dataloader: torch.utils.data.DataLoader,
                  loss_fn: torch.nn.Module,
                  accuracy_fn):
  test_loss ,test_acc = 0 ,0

  model.eval()

  with torch.inference_mode():
    for X_test,y_test in dataloader:

      test_pred = model(X_test)

      test_loss += loss_fn(test_pred , y_test)
      test_acc += accuracy_fn(y_test , test_pred.argmax(dim=1))

    test_loss /= len(dataloader)
    test_acc /= len(dataloader)

  print(f"Test Loss: {test_loss:.4f} | Test Accuracy: {test_acc:.4f}")

In [ ]:
torch.manual_seed(42)

epochs = 3
time_start = timer()
for epoch in tqdm(range(epochs)):
  print(f"Epoch {epoch}\n -------------")
  training_model(model_1,
                 train_dataloader,
                 loss_fn,
                 optimizer,
                 accuracy_fn)
  testing_model(model_1,
                 test_dataloader,
                 loss_fn,
                 accuracy_fn)

time_end = timer()

time_taken = print_train_time(time_start , time_end)

  0%|          | 0/3 [00:00<?, ?it/s]

Epoch 0
 -------------
Training Loss: 1.1612 | Training Accuracy: 59.7167
Test Loss: 0.7217 | Test Accuracy: 72.8035
Epoch 1
 -------------
Training Loss: 0.6333 | Training Accuracy: 77.2817
Test Loss: 0.6045 | Test Accuracy: 78.3147
Epoch 2
 -------------
Training Loss: 0.5610 | Training Accuracy: 80.2850
Test Loss: 0.5701 | Test Accuracy: 79.8822
The time taken is: 28.651483722000023


In [ ]:
eval_model(model_1,
           test_dataloader,
           loss_fn,
           accuracy_fn)

{'model': 'FashionMNISTModel_1',
 'model loss': 0.570142924785614,
 'model accuracy': 79.88218849840256}

## MODEL 3

## Now we will start building a ConvNet based computer vision system
* We will try to replicate this convnet in pytorch - https://poloclub.github.io/cnn-explainer/

In [ ]:
class FashionMNISTModel2(nn.Module):
  '''
  Model architecture that replicates TinyVGG
  '''
  def __init__(self, in_shape:int , hidden_units:int , output_shape:int):
    super().__init__()

    self.conv_block1 = nn.Sequential(
        nn.Conv2d(in_shape,
                  hidden_units,
                  kernel_size = 3,
                  stride = 1,
                  padding = 1),
        nn.ReLU(),
        nn.Conv2d(hidden_units,
                  hidden_units,
                  kernel_size = 3,
                  stride = 1,
                  padding = 1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size = 2)
     )

    self.conv_block2 = nn.Sequential(
        nn.Conv2d(hidden_units,
                  hidden_units,
                  kernel_size = 3,
                  stride = 1,
                  padding = 1),
        nn.ReLU(),
        nn.Conv2d(hidden_units,
                  hidden_units,
                  kernel_size = 3,
                  stride = 1,
                  padding = 1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size = 2)
     )

    self.ClassifierLayer = nn.Sequential(
        nn.Flatten(),
        nn.Linear(hidden_units*49,
                  output_shape)
    )

  def forward(self , x):
    x = self.conv_block1(x)
    # print(x.shape)
    x = self.conv_block2(x)
    # print(x.shape)
    x = self.ClassifierLayer(x)
    return x

In [ ]:
model_2 = FashionMNISTModel2(in_shape = 1,
                             hidden_units = 30,
                             output_shape = len(class_names))

## Setting up `Conv2D()`

In [ ]:
  loss_fn = nn.CrossEntropyLoss()
  optimizer = torch.optim.SGD(params = model_2.parameters(),
                              lr = 0.01)

In [ ]:
torch.manual_seed(42)

epochs = 30

time_start = timer()

for epoch in tqdm(range(epochs)):
  print(f"Epoch {epoch}\n -------------")
  training_model(model_2,
                 train_dataloader,
                 loss_fn,
                 optimizer,
                 accuracy_fn)
  testing_model(model_2,
                 test_dataloader,
                 loss_fn,
                 accuracy_fn)

time_end = timer()

time_taken = print_train_time(time_start , time_end)

  0%|          | 0/30 [00:00<?, ?it/s]

Epoch 0
 -------------
Training Loss: 1.1652 | Training Accuracy: 57.7317
Test Loss: 0.5617 | Test Accuracy: 79.6725
Epoch 1
 -------------
Training Loss: 0.4965 | Training Accuracy: 81.8767
Test Loss: 0.4616 | Test Accuracy: 82.6178
Epoch 2
 -------------
Training Loss: 0.4122 | Training Accuracy: 85.1683
Test Loss: 0.4008 | Test Accuracy: 85.6030
Epoch 3
 -------------
Training Loss: 0.3732 | Training Accuracy: 86.5517
Test Loss: 0.3676 | Test Accuracy: 86.6014
Epoch 4
 -------------
Training Loss: 0.3470 | Training Accuracy: 87.4117
Test Loss: 0.3517 | Test Accuracy: 87.3702
Epoch 5
 -------------
Training Loss: 0.3271 | Training Accuracy: 88.2233
Test Loss: 0.3384 | Test Accuracy: 88.0491
Epoch 6
 -------------
Training Loss: 0.3116 | Training Accuracy: 88.7717
Test Loss: 0.3440 | Test Accuracy: 87.7596
Epoch 7
 -------------
Training Loss: 0.3003 | Training Accuracy: 89.0833
Test Loss: 0.3235 | Test Accuracy: 88.2688
Epoch 8
 -------------
Training Loss: 0.2893 | Training Accuracy

In [ ]:
model_eval